-- MySQL Script generated by MySQL Workbench
-- Wed Mar 23 13:12:17 2022

-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

CREATE SCHEMA IF NOT EXISTS `nominapp` DEFAULT CHARACTER SET 'utf8' ;
USE `nominapp` ;

-- -----------------------------------------------------
-- Table `nominapp`.`Banco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nominapp`.`Banco` ;

CREATE TABLE IF NOT EXISTS `nominapp`.`Banco` (
  `codInstBanca` VARCHAR(3) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`codInstBanca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nominapp`.`Cargo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nominapp`.`Cargo` ;

CREATE TABLE IF NOT EXISTS `nominapp`.`Cargo` (
  `codCargo` VARCHAR(3) NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`codCargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nominapp`.`Complemento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nominapp`.`Complemento` ;

CREATE TABLE IF NOT EXISTS `nominapp`.`Complemento` (
  `codTipoComplemento` VARCHAR(3) NOT NULL,
  `descripcion` VARCHAR(100) NULL,
  `monto` VARCHAR(45) NULL,
  PRIMARY KEY (`codTipoComplemento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nominapp`.`DenominacionCargo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nominapp`.`DenominacionCargo` ;

CREATE TABLE IF NOT EXISTS `nominapp`.`DenominacionCargo` (
  `codCargoDen` VARCHAR(3) NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  `tipoCargo` ENUM('OB', 'PD', 'AN') NULL,
  PRIMARY KEY (`codCargoDen`))

ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nominapp`.`Departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nominapp`.`Departamento` ;

CREATE TABLE IF NOT EXISTS `nominapp`.`Departamento` (
  `codDepartamento` VARCHAR(3) NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`codDepartamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nominapp`.`EstadoCivil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nominapp`.`EstadoCivil` ;

CREATE TABLE IF NOT EXISTS `nominapp`.`EstadoCivil` (
  `codEdoCivil` VARCHAR(3) NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`codEdoCivil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nominapp`.`Estados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nominapp`.`Estados` ;

CREATE TABLE IF NOT EXISTS `nominapp`.`Estados` (
  `codEstado` VARCHAR(3) NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`codEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nominapp`.`NivelAcademico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nominapp`.`NivelAcademico` ;

CREATE TABLE IF NOT EXISTS `nominapp`.`NivelAcademico` (
  `codNivelAcademico` VARCHAR(3) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`codNivelAcademico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nominapp`.`TipoNomina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nominapp`.`TipoNomina` ;

CREATE TABLE IF NOT EXISTS `nominapp`.`TipoNomina` (
  `codTipoNomina` VARCHAR(3) NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`codTipoNomina`))
ENGINE = InnoDB;

USE `nominapp`;


-- -----------------------------------------------------
-- Table `nominapp`.`Persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nominapp`.`Persona` ;

CREATE TABLE IF NOT EXISTS `nominapp`.`Persona` (
  `idPersona` INT NOT NULL AUTO_INCREMENT,
  `cedula` VARCHAR(10) NOT NULL,
  `status` ENUM('ACT', 'SUS', 'EGR') NOT NULL COMMENT 'ACT: Activo; SUS: Suspendido; EGR: Egresado',
  `nombres` VARCHAR(50) NOT NULL,
  `apellidos` VARCHAR(50) NOT NULL,
  `sexo` ENUM('M', 'F') COMMENT 'M: Masculino; F: Femenino',
  `codDepartamento` VARCHAR(3) NOT NULL,
  `codCargo` VARCHAR(3) NOT NULL,
  `codCargoDen` VARCHAR(3) NOT NULL,
  `fecNac` DATE NOT NULL,
  `direccion` VARCHAR(255),
  `ultimoTrabajoPublico` VARCHAR(50),
  `telefLocal` VARCHAR(50),
  `telefMovil` VARCHAR(50) NOT NULL,
  `codEstado` VARCHAR(3) NOT NULL,
  `lugarNacimiento` VARCHAR(255),
  `codEdoCivil` VARCHAR(3) NOT NULL,
  `tipoSangre` VARCHAR(3),
  `email` VARCHAR(50),
  `nombrePersonaEmergencia` VARCHAR(50),
  `telefPersonaEmergencia` VARCHAR(50),
  `codNivelAcademico` VARCHAR(3) NOT NULL,
  `tituloAcademico` VARCHAR(50),
  `fecIngreso` DATE NOT NULL,
  `aniosAPN` INT DEFAULT 0 COMMENT 'Años de antiguedad en otras instituciones públicas',
  `lugarSufraga` VARCHAR(255) NOT NULL,
  `codInstBanca` VARCHAR(3) NOT NULL,
  `tipoCuenta` ENUM('CC', 'CA') NOT NULL DEFAULT 'CC' COMMENT 'CC: Cuenta corriente; CA: Cuenta ahorro',
  `numCuenta` VARCHAR(255) NOT NULL,
  `numHijos` INT DEFAULT 0,
  `indBecaEscolar` ENUM('S', 'N') NOT NULL COMMENT 'S: Si; N: No',
  `indDiscapacidad` ENUM('S', 'N') NOT NULL COMMENT 'S: Si; N: No',
  `indVacaciones` ENUM('S', 'N') NOT NULL COMMENT 'S: Si; N: No',
  `codTipoNomina` VARCHAR(3) NOT NULL,
  `observaciones` VARCHAR(500),
  `encargaduria`  DOUBLE DEFAULT 0,
  `bonoProteico`  DOUBLE DEFAULT 0
  PRIMARY KEY (`idPersona`),
  CONSTRAINT `fk_Persona_Cargo1`
    FOREIGN KEY (`codCargo`)
    REFERENCES `nominapp`.`Cargo` (`codCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_NivelAcademico1`
    FOREIGN KEY (`codNivelAcademico`)
    REFERENCES `nominapp`.`NivelAcademico` (`codNivelAcademico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_Estados1`
    FOREIGN KEY (`codEstado`)
    REFERENCES `nominapp`.`Estados` (`codEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_EstadoCivil1`
    FOREIGN KEY (`codEdoCivil`)
    REFERENCES `nominapp`.`EstadoCivil` (`codEdoCivil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_Banco1`
    FOREIGN KEY (`codInstBanca`)
    REFERENCES `nominapp`.`Banco` (`codInstBanca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_Departamento1`
    FOREIGN KEY (`codDepartamento`)
    REFERENCES `nominapp`.`Departamento` (`codDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_TipoNomina1`
    FOREIGN KEY (`codTipoNomina`)
    REFERENCES `nominapp`.`TipoNomina` (`codTipoNomina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_DenomicacionCargo1`
    FOREIGN KEY (`codCargoDen`)
    REFERENCES `nominapp`.`DenominacionCargo` (`codCargoDen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Persona_Cargo1_idx` ON `nominapp`.`Persona` (`codCargo` ASC);

CREATE INDEX `fk_Persona_NivelAcademico1_idx` ON `nominapp`.`Persona` (`codNivelAcademico` ASC);

CREATE INDEX `fk_Persona_Estados1_idx` ON `nominapp`.`Persona` (`codEstado` ASC);

CREATE INDEX `fk_Persona_EstadoCivil1_idx` ON `nominapp`.`Persona` (`codEdoCivil` ASC);

CREATE INDEX `fk_Persona_Banco1_idx` ON `nominapp`.`Persona` (`codInstBanca` ASC);

CREATE INDEX `fk_Persona_Departamento1_idx` ON `nominapp`.`Persona` (`codDepartamento` ASC);

CREATE INDEX `fk_Persona_cedula` ON `nominapp`.`Persona` (`cedula` ASC);

CREATE INDEX `fk_Persona_TipoNomina1_idx` ON `nominapp`.`Persona` (`codTipoNomina` ASC);

CREATE INDEX `fk_Persona_DenomicacionCargo1_idx` ON `nominapp`.`Persona` (`codCargoDen` ASC);


-- -----------------------------------------------------
-- Table `nominapp`.`Nomina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nominapp`.`Nomina` ;

CREATE TABLE IF NOT EXISTS `nominapp`.`Nomina` (
  `idNomina` INT NOT NULL AUTO_INCREMENT,
  `numQuincena` VARCHAR(2) NULL,
  `anio` VARCHAR(20) NULL,
  `mes` VARCHAR(20) NULL,
  PRIMARY KEY (`idNomina`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `nominapp`.`NominaDetal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nominapp`.`NominaDetal` ;

CREATE TABLE IF NOT EXISTS `nominapp`.`NominaDetal` (
  `idNominaDetal` INT NOT NULL AUTO_INCREMENT,
  `idNomina` INT NOT NULL,
  `cedula` VARCHAR(10) NOT NULL,
  `salario` DOUBLE NULL,
  `aniosFMA` INT NULL,
  `aniosAPN` INT NULL,
  `antiguedad` INT NULL,
  `primaAnt` DOUBLE NULL,
  `primaProf` DOUBLE NULL,
  `beca` INT NULL,
  `numHijos` INT NULL,
  `diasLaborales` INT NULL,
  `sueldoBase` DOUBLE NULL,
  `primaAntAsig` DOUBLE NULL,
  `primaProfAsig` DOUBLE NULL,
  `encargaduria` DOUBLE NULL,
  `primaHijos` DOUBLE NULL,
  `primaBeca` DOUBLE NULL,
  `primaDis` DOUBLE NULL,
  `totRemuneracion` DOUBLE NULL,
  `bonoVacc` DOUBLE NULL,
  `complementoSueldo` DOUBLE NULL,
  `complementoEspecial` DOUBLE NULL,
  `bonoProteico` DOUBLE NULL,
  `retroActivo` DOUBLE NULL,
  `seguroSocial` DOUBLE NULL,
  `faov` DOUBLE NULL,
  `rpe` DOUBLE NULL,
  `tesoreriaSs` DOUBLE NULL,
  `appSeguroSocial` DOUBLE NULL,
  `appFaov` DOUBLE NULL,
  `appRpe` DOUBLE NULL,
  `appTesoreria` DOUBLE NULL,
  `totAsignacion` DOUBLE NULL,
  `toodeduccion` DOUBLE NULL,
  `totApp` DOUBLE NULL,
  `netoCobrar` DOUBLE NULL,
  PRIMARY KEY (`idNominaDetal`),
  CONSTRAINT `fk_NominaDetal_Persona1`
    FOREIGN KEY (`Cedula`)
    REFERENCES `nominapp`.`Persona` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NominaDetal_Nomina1`
    FOREIGN KEY (`idNomina`)
    REFERENCES `nominapp`.`Nomina` (`idNomina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_NominaDetal_Persona1_idx` ON `nominapp`.`NominaDetal` (`Cedula` ASC);

CREATE INDEX `fk_NominaDetal_Nomina1_idx` ON `nominapp`.`NominaDetal` (`idNomina` ASC);


-- -----------------------------------------------------
-- Table `nominapp`.`PrimaAntiguedad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nominapp`.`PrimaAntiguedad` ;

CREATE TABLE IF NOT EXISTS `nominapp`.`PrimaAntiguedad` (
  `anioAntiguedad` INT NOT NULL,
  `prima` DOUBLE NULL,
  PRIMARY KEY (`anioAntiguedad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nominapp`.`PrimaProfesional`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nominapp`.`PrimaProfesional` ;

CREATE TABLE IF NOT EXISTS `nominapp`.`PrimaProfesional` (
  `idPrimaProfesional` INT NOT NULL AUTO_INCREMENT,
  `prima` DOUBLE NULL,
  `codNivelAcademico` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`idPrimaProfesional`),
  CONSTRAINT `fk_PrimaProfesional_NivelAcademico`
    FOREIGN KEY (`codNivelAcademico`)
    REFERENCES `nominapp`.`NivelAcademico` (`codNivelAcademico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_PrimaProfesional_NivelAcademico_idx` ON `nominapp`.`PrimaProfesional` (`codNivelAcademico` ASC);


-- -----------------------------------------------------
-- Table `nominapp`.`Tabulador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nominapp`.`Tabulador` ;

CREATE TABLE IF NOT EXISTS `nominapp`.`Tabulador` (
  `idTabulador` INT NOT NULL AUTO_INCREMENT,
  `codCargoDen` VARCHAR(3) NOT NULL,
  `mtomin` DOUBLE NULL COMMENT 'Para:\nAlto nivel(AN): mtomin será montoBs y mtomax será anteriores, rango1 y rango2 vacios.\nPersonal administrativo(PA): mtomin sera monto tabulador. mtomax ira vacio.\nObreros(O): mtomin será monto mínimo y mtomax será monto máximo, rango1 y rango 2 vacios.\n',
  `mtomax` DOUBLE NULL COMMENT 'Para:\nAlto nivel(AN): mtomin será montoBs y mtomax será anteriores, rango1 y rango2 vacios.\nPersonal administrativo(PA): mtomin sera monto tabulador. mtomax ira vacio.\nObreros(O): mtomin será monto mínimo y mtomax será monto máximo, rango1 y rango 2 vacios.',
  `rango1` INT NULL,
  `rango2` INT NULL,
  PRIMARY KEY (`idTabulador`),
  CONSTRAINT `fk_Tabulador_DenominacionCargo1`
    FOREIGN KEY (`codCargoDen`)
    REFERENCES `nominapp`.`DenominacionCargo` (`codCargoDen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Tabulador_DenomicacionCargo1_idx` ON `nominapp`.`Tabulador` (`codCargoDen` ASC);

-- -----------------------------------------------------
-- Table `nominapp`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nominapp`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `nominapp`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `cedula` VARCHAR(10) NOT NULL,
  `password` VARCHAR(100),
  `codRol` ENUM('ANF', 'ANN', 'ANI', 'JEF') COMMENT 'ANF: Analista de ficha técnica; ANN: Analista de nómina; ANI: Analista integral; JEF: Jefe de departamento',
  `status` ENUM('ACT', 'SUS') NOT NULL COMMENT 'ACT: Activo; SUS: Suspendido',
  `created` DATE,
  PRIMARY KEY (`idUsuario`),
  CONSTRAINT `fk_Usuario_Persona`
    FOREIGN KEY (`cedula`)
    REFERENCES `nominapp`.`Persona` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;